- name: post deploy playbook
  hosts: localhost
  tasks:
    - name: get running ansible env variables
      set_fact:
        workspace_id: "{{ lookup('env', 'workspace_id') }}"
        ibmcloud_api_key: "{{ lookup('env', 'ibmcloud_api_key')}}" # pragma: allowlist secret
        cluster_id: "{{ lookup('env', 'cluster_id') }}"
        access_key: "{{ lookup('env', 'access_key') }}"
        existing_access_key_secret_name: "{{ lookup('env', 'existing_access_key_secret_name') }}"
    - name: Fetch Instance ID from access_key
      ansible.builtin.shell: |
        ibmcloud login --apikey "{{ ibmcloud_api_key }}" --no-region -q >/dev/null 2>&1 && ibmcloud resource service-keys -o json | jq -r --arg access_key "{{ access_key }}" '.[] | select(.credentials."Sysdig Access Key" == $access_key).source_crn'
      register: ibmcloud_auth_result
      changed_when: false
      ignore_errors: yes
      when: access_key is defined and access_key is not none and access_key != ''
    - name: Fetch Instance ID from existing_access_key_secret_name
      ansible.builtin.shell: |
        ibmcloud login --apikey "{{ ibmcloud_api_key }}" --no-region -q >/dev/null 2>&1 && ibmcloud resource service-key "{{ existing_access_key_secret_name }}" -o json | jq -r --arg name "{{ existing_access_key_secret_name }}" '.[] | select(.name == $name).source_crn'
      register: ibmcloud_auth_result
      changed_when: false
      ignore_errors: yes
      when: existing_access_key_secret_name is defined and existing_access_key_secret_name is not none and existing_access_key_secret_name != ''
    - name: Extract value instance ID
      set_fact:
        instance: "{{ ibmcloud_auth_result.stdout | regex_search('[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}') }}"
      ignore_errors: yes
    - name: Attach tags
      ansible.builtin.shell: |
        ibmcloud login --apikey "{{ ibmcloud_api_key }}" --no-region -q && ibmcloud resource tag-attach --resource-id "$(ibmcloud resource service-instance "{{ cluster_id }}" --crn -q)" --tag-names "monitoring-instance:{{ instance }},mwp-workspace:{{ workspace_id }}" >/dev/null 2>&1
      register: ibmcloud_auth_result
      changed_when: false
      ignore_errors: yes
